### ISSUE TITLE
一些想法

### ISSUE THREAD

**Issue by i5ting** [starkwang/quickr#2]
- 日志做成中间件就好了，内置有点重，且扩展麻烦。
- 加debug模块，错误处理等处加好就好了。
- Model/Service层意义不大，可以再包一个框架，这个保持小而美就好了
- chokidar、commander这些包还是有点大。能不用就不用

**Comment by starkwang** [comment]
哈哈非常感谢狼叔的建议~

1这个是选择后的决定，因为我还暂时没有打算引入「中间件」这个概念，所以一些功能只能先内置
2这个正在做~
3这个我也同意的，并不打算做 Model/Service
4这个为了一些特定的功能（热重载、命令行），只能引入了，node的包体积个人感觉没有那么敏感
